---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: db-password
  namespace: default
spec:
  encryptedData:
    password: AgAu05AfyVQeOiy8Lz3TZ6V1iOnoyTrb/dakODSuPZpedBKfdHVZlPZ6g0FJBQHPT4Iby6lH4zrFSBV44Bav2HPg3NLEDeyBXSw0ELZ9tKytXi9HtV8cZMqQ7gbB/CNWkbPS/YeJir1KUfIQsP5ioxjnfNmg8sx22q6tckT0RhjbBIS5T+RmmRP7FmQbZQI31jv1AbNV+21qoNAi1I4XLFegkvIhjfyTAbLosmm/YgrxEh2sUjgNIvsiRokY1hSOl9Uv8e7wcXHGRatmjgGvqJHfQbFmPN6+rUcZYd9kPl30tAZGdY+glQ+BPr3kzNZ8JlqyqmT2KnFkvSTAlGCdLkXj+aELvFxrVtdFOl1B6RXdQUGWJH2kaOTMQb3i+HtCvPrlD73ksyUGHgz9wJTKorUbkbm8tceHWR8z5EJEeR/HZcrEZN1GEXXndrvxLPdJyDMJsht+r7d6MA0HLgqjNWIaTUbWtZqqTt6qjr5B3eKS+aWb/B0uG6m7Bo7AWqAMFnttryR/Dl23GuUJB7AKL/lxSnXQ2l75o7EFk8w7SltXhPKH4TiqgkjFcTuFmwK/3Crb7tKbTotSq/X+30D2VbAvf26ZX5KBa4ZJtx254CuaKDJ9KePVkWOfcTYC39cDGU4Unfx0Gg2qjahrSFvWDLh8S2Kg7A0X14KZRE7z3hbnwnhonbBDJMVDX3JAgKrQubRQQonS4MkGpk6OLg6qYws=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: db-password
      namespace: default
