---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-password
  namespace: default
spec:
  encryptedData:
    password: AgCKNT0iSgz2/Q6W4hw+lejqtWoYbXEe8rkGDPJ63QqJfMIzobeWOXiDQJ98XqWnuUeVM91u/QgPOjog98TsHCiWc0QFsDsh+TgV3FHiMfEQRbaijQpE4Jj8i7ivzw8EbauoE1z61XWLzaNvdsWtxDHel3seKo3rpjuMdw6VLu9xesl/iOuBfwW6Su4sD9p78jEXGoERw9eOpgkjNlKA1V2Ix75LNYFOQApHeuOpL6UH42a1AoEOwJmiM5HC/D+KfpCbFJoneejtDLqB9nUpCnUBM/ruULCpD16Hkt2LswpTP5VY2Su+yHEw0goKfNH9YVZ2ySS8gbznCYVuZYfrXgqPU7wUT4++3YUjqvlTmTHFvDFCF1zokVZHNCupT8T8PcNodftIE86dxFm0+safDZqCVqISG1UMV9C87QpgbUlBG0Pb1a6M7PhwjSvZsycfIpL5SBW+gFzG4ARtLbHmRzk7JNEnkYHeYhpea0MIPYD+70eFqUJAZm5ZwwVnTqtK9x/9tHcGQd0nFy/uciFIQnlHIpWN7RiT5w8FUgk8XOe402hr/wYgpJEOLbiijuCTW1207T4cen+WrlgMgmYQYnF1r9+bq+uq5jCm2zQPGmG1WBKauCnASm2ShUQVMdRv9Muue1SI4HS18Ek/5WRq1oR6Z8iMX1+3QgPRkAvYgLRnoBG5js4du2Oh57sjxuBdPfH7QGosoMOu83Mx
  template:
    metadata:
      creationTimestamp: null
      name: db-password
      namespace: default
