---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-password
  namespace: sealed-secrets
spec:
  encryptedData:
    password: AgBdiQJsSDdZLO08Gnt8Ha7SSPta1ex0FZc2NcrnwwrpizvWZjfT2pCXrS+guyv65bVKI/LaQpJfXRjdzN19Safh76Lt3FJsN0sP76atxLzxIAKF4yx6nu99hLH2shz7kw0SrMgnzQH357mGgBsXlYU5i4ZXV4pDRhBrSB1FnO8I+8BwOeQsiz0MX6U42v+XgS7rSrVlrQMtS4tvT7X6xjqbixvi7O3EnMd4Y0o9H6aT5Txqe3ZM9mlKwoOOymT8ExFX2uFH+U8hCp1pTDvWNDZcJc0h7/2wKqcNc30r1uV1ap8RUJiu5OA/TqBWmBM2W2LhqMC3o/BQCxFcOswdkIix1FCP47+1fMDR7W8qYL6KCpljRljFvIVUnX9HwK5CBOnmDkKbTdpBapsEQmDoCTpwgUHhXAm5rfM2//fE5vKG8R0gwGeN8EWYRE3zAlfnwERLRV+GXcYQqTEJJ+swVukw/sexkPBkwue1NDjtPdht0nIaMsmCgYCJE1ZBAOSkSp+Wk4fj5J5iq5LkIfPkbdrBOuTs/EEPXQV3RdC7tF20cxv1HxLKSsDgkMn+f6UGBlYNuAos1byg1gGBCFTRDnMoX90U+hffTzd+6w3Xl10zqoX94Aoiv5Q4daS5ije8zqji4gr5/0aB4jmijoj/iO+YJklnZseIX2X8t34EE08QyOjLTY/YNDdTnkeM8qf8U2DqZNaG8Xgpluo+
  template:
    metadata:
      creationTimestamp: null
      name: db-password
      namespace: sealed-secrets
