apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: default
spec:
  encryptedData:
    secret-value: AgA4SD8...
  template:
    metadata:
      name: app-secret
      namespace: default
    type: Opaque
